name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Cache NVD Database
        id: cache-nvd
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: nvd-cache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            nvd-cache-${{ runner.os }}-

#      - name: Cache Maven packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean verify
        env:
          NVD_NIST_APIKEY: ${{ secrets.NVD_NIST_APIKEY }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

      - name: Prep package
        run: mkdir staging && cp target/*.jar staging

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging

      - name: Cache NVD Database
        id: cache-nvd
        uses: actions/cache/save@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: nvd-cache-${{ runner.os }}-${{ github.run_id }}
